# Generated by Django 3.2.7 on 2021-09-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productmodel_price'),
        ('shop', '0002_auto_20210914_2304'),
    ]

    operations = [
    ]
