# Generated by Django 3.2.7 on 2021-09-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_merge_20210915_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Cart List'},
        ),
    ]
