# Generated by Django 3.2.7 on 2021-09-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shippingaddressmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Delivery cost',
                'verbose_name_plural': 'Delivery cost',
            },
        ),
    ]
