# Generated by Django 3.2.7 on 2021-09-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_cartmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
