# Generated by Django 3.2.7 on 2021-09-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_productmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='user',
        ),
    ]
