# Generated by Django 3.2.7 on 2021-09-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_favoritesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
