# Generated by Django 3.2.7 on 2021-09-27 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_ordermodel_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cartmodel'),
        ),
    ]
