# Generated by Django 3.2.7 on 2021-09-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_ordermodel_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cartmodel'),
        ),
    ]
