# Generated by Django 3.2.7 on 2021-09-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_ordermodel_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='cart',
        ),
    ]
